# Generated by Django 5.1.4 on 2024-12-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('hoteType', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_No', models.IntegerField()),
                ('roomType', models.CharField(max_length=100)),
                ('price_per_room', models.FloatField(default=0.0)),
                ('available_room', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.hotel')),
            ],
        ),
    ]
